### ISSUE TITLE
alvex-uploader formcontrol is not working

### ISSUE THREAD

**Issue by yregaieg** [ITDSystems/alvex#1]
When I try to upload new documents to my package items inside a workflow task, I hit some problems with the uploader.
Primary investigations suggests there is some broken references (incoherence between js/css paths from share-form-config and the real project structure in com.alvexcore.share:utils:1.1).
I will investigate the issue further and follow up with a PR soon.

**Comment by ArgentumHeart** [comment]
Hello! Yes, there were some issues with paths in different places. Can you try again? Keep in mind, that some icons can still be broken.

**Comment by yregaieg** [comment]
Thank you for your quick reply!
I can see you detected some incorrect paths I did not detect, and missed few I did detect ! So I made a PR on `alvex-uploader` project to fix them.
