### ISSUE TITLE
Recieve mail

### ISSUE THREAD

**Issue by ABakumenko** [ITDSystems/alvex#10]
Hello,
I have a problem with recieving mail, when I Uncheck checkbox 'recieve notification', anyway, they are sent by alfresco.
I have Alfresco Community v5.2.0 and alvex-3.0-20170502.123755-241.zip

**Comment by aviriel** [comment]
Not Alvex bug, this checkbox relates only to default Alfresco notifications on sites, all other messages will still be sent.
