### ISSUE TITLE
How can i build amp instead of jar?

### ISSUE THREAD

**Issue by p4535992** [ITDSystems/alvex#13]
Hi, I must misunderstood something on the documentation with the following command i succesfully build the jars file:

`
mvn -P custom-workflows,orgchart,uploader,project-management,manager-dashboard-tasks,inform-policy,workflow-permissions,infavorites-document-association,datagrid,masterdata,middle-name,business-calend clean package
`

but i need to generate the amps file instead, from the documentation seem possible, but i don't get it what command use to generate the zip file with amp instead of jars.
I must simply modify the xml context file of the assembly plguin for that? or i miss some profile settings?

**Comment by aviriel** [comment]
Hi,

You cannot build amp in this way. You can build AMP for every component independently using `mvn clean install` following https://github.com/ITDSystems/alvex#build-component-from-source.
