### ISSUE TITLE
Aikau Forms Runtime Support Dependency Issue

### ISSUE THREAD

**Issue by da1ight** [ITDSystems/alvex#15]
Здравствуйте,

Задача:
Запустить Alfresco с расширениями Alvex, что посмотреть на систему и определить, подходит ли она для наших нужд.
Что было сделано:
1. Запускаем PostgreSQL
```
# docker run --name='postgres' -e 'POSTGRES_PASSWORD=alfresco' -e 'POSTGRES_USER=alfresco' -e 'POSTGRES_DB=alfresco' -d postgres
```
2. Запускаем Alfresco, ликуем с базой, монтируем volume-ы content\alf_data\modules
```
# docker run --name='alfresco' -d -it --rm -p 445:445 -p 7070:7070 -p 8080:8080 -v '/home/core/alfresco/content:/content' -v '/home/core/alfresco/data:/alfresco/alf_data' -v '/home/core/alfresco/modules:/alfresco/modules' -e 'CONTENT_STORE=/content' -e 'DB_KIND=postgresql' -e 'DB_HOST=postgres' -e 'DB_USERNAME=alfresco' -e 'DB_PASSWORD=alfresco' -e 'DB_NAME=alfresco' --link postgres:postgres gui81/alfresco
```
3. Клонируем репо
```
# git clone https://github.com/ITDSystems/alvex.git
```
4. Собираем
```
# cd ./alvex
# docker run --rm -v "$(pwd)":/opt/maven -w /opt/maven maven:3.3.9-jdk-8 mvn -P uploader,manager-dashboard-tasks,inform-policy,workflow-permissions,infavorites-document-association,datagrid,masterdata,middle-name,business-calendar,aikau-components,registers clean package
```
5. Копируем артефакты
```
# cd target/
# unzip alvex-3.0-SNAPSHOT.zip
# cd repo/
# cp * ../../../alfresco/modules/platform/
# cd ../share
# cp * ../../../alfresco/modules/share/
```
6. Перезапускаем Alfresco

Далее поскольку нас больше всего интересуют реестры документов полез смотреть на них.
<img width="1278" alt="screen shot 2018-06-16 at 12 04 39" src="https://user-images.githubusercontent.com/15888167/41497414-8706067c-715d-11e8-9207-3de47398ff50.png">
При нажатии на кнопку `Новая Запись` ничего не происходит.

Начал смотреть дальше, увидел что во многих модулях присутствует вот такая зависимость.

> Aikau Forms Runtime Support of the same version as Aikau (it's not inside Alvex ZIP or AMP, be sure to install it manually)

Соответсвенно предполагаю, что проблема  в ней. Подскажите, как я могу ее установить вручную?

**Comment by aviriel** [comment]
Если форма не открывается, то проблема правда в отсутствии Aikau Forms Runtime Support. Посмотрите, какая у вас версия Aikau, скачайте из https://artifacts.alfresco.com/nexus/content/repositories/public/org/alfresco/aikau-forms-runtime-support/ JAR той же версии и положите его в modules/share/

**Comment by da1ight** [comment]
Спасибо, это мне помогло.
