### ISSUE TITLE
Include Alvex to your project via maven configuration

### ISSUE THREAD

**Issue by u-s-e-r-1-2-3** [ITDSystems/alvex#16]
Использовал рекомендации по включению Alvex в Alfresco SDK(3.0.1) согласно https://github.com/ITDSystems/alvex. Проект собирается, но компоненты Alvex в нем отсутствуют. С чем может быть связана эта проблема?

**Comment by aviriel** [comment]
Вероятно Вы не добавили в dependency <classifier>installable</classifier>, который отвечает за то, собирать ли зависимости внутри пакета

**Comment by u-s-e-r-1-2-3** [comment]
фрагмент из шары
                <dependency>
                    <groupId>com.alvexcore.share</groupId>
                    <artifactId>utils</artifactId>
                    <version>1.19-SNAPSHOT</version>
                    <classifier>installable</classifier>
                </dependency>
в локальный maven все скачалось, либы в проекте пристутсвуют, но в таргете ничего от альвекса нет

**Comment by aviriel** [comment]
Вы jar собираете? Тогда и не будет, оно не умеет включать jar в jar.

**Comment by u-s-e-r-1-2-3** [comment]
Добавлял зависимости Alvex в Alfresco All-in-One sdk 3.0.1. Видимо здесь нужны еще какие-то изменения в pom-ах

**Comment by aviriel** [comment]
но скрипт сборки собирает AMP или JAR?

**Comment by u-s-e-r-1-2-3** [comment]
jar

**Comment by aviriel** [comment]
JAR не умеют включать друг друга. Поэтому все нужные зависимости скачиваются, но не собираются. Только в AMP можно собрать все JAR внутри.
