### ISSUE TITLE
Question: Generate .jar file

### ISSUE THREAD

**Issue by errmerrged** [ITDSystems/alvex#8]
Hello, I'm trying to generate a .jar file after tweaking some codes in the project using this command `mvn -P make-jar clean install`. It generates two(2) .jar files `datagrid-1.0-SNAPSHOT.jar` and `datagrid-1.0-SNAPSHOT-installable.jar`. Which .jar should I move to /alfresco/WEB-INF/lib?

**Comment by aviriel** [comment]
Use -installable one. The second one should be used together with many files outside of the JAR.

**Comment by errmerrged** [comment]
Oh, thanks
